import { notFound } from 'next/navigation';
import { ArrowLeft } from 'lucide-react';
import Link from 'next/link';
import { AppShell } from '@/components/layout/AppShell';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { prisma } from '@/lib/db/prisma';

export default async function TeamDetailPage({params}:{params:Promise<{id:string}>}){const {id}=await params;const team=await prisma.team.findUnique({where:{id},include:{group:true,homeMatches:{include:{awayTeam:true}},awayMatches:{include:{homeTeam:true}}}});if(!team)return notFound();return <AppShell><Link href="/equipos" className="inline-flex items-center gap-2 text-sm text-white/45 hover:text-white"><ArrowLeft className="size-4"/>Equipos</Link><div className="mt-5 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><Card><CardContent className="p-6"><div className="flex items-center gap-4"><div className="grid size-16 place-items-center rounded-2xl text-xl font-black text-black" style={{backgroundColor:team.badgeColor}}>{team.shortName}</div><div><div className="text-2xl font-black">{team.name}</div><Badge variant="muted">{team.group.name}</Badge></div></div><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{[['Puntos',team.points],['Victorias',team.wins],['Empates',team.draws],['Derrotas',team.losses],['GF',team.goalsFor],['GC',team.goalsAgainst]].map(([a,b])=><div key={String(a)} className="rounded-xl bg-white/[.03] p-3"><div className="text-xs text-white/35">{a}</div><div className="mt-1 text-xl font-black">{b}</div></div>)}</div></CardContent></Card><Card><CardContent><h2 className="mb-4 font-bold">Forma y próximos cruces</h2><div className="space-y-2">{[...team.homeMatches.slice(0,3).map(m=>({id:m.id,op:m.awayTeam.name,side:'Local'})),...team.awayMatches.slice(0,3).map(m=>({id:m.id,op:m.homeTeam.name,side:'Visitante'}))].map(m=><div key={m.id} className="flex items-center justify-between rounded-xl bg-white/[.03] p-3"><div className="font-medium">{m.op}</div><Badge variant="muted">{m.side}</Badge></div>)}</div></CardContent></Card></div></AppShell>}
