'use client';
import { useEffect, useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';

function marketLabel(market:string){return ({winner:'Ganador',goals:'Goles 2.5',btts:'Ambos marcan',exact:'Resultado exacto'} as Record<string,string>)[market]??market}
function selectionLabel(selection:string,match:any){return ({HOME:match.homeTeam.shortName,AWAY:match.awayTeam.shortName,DRAW:'Empate',OVER_2_5:'Más de 2.5',UNDER_2_5:'Menos de 2.5',YES:'Sí',NO:'No'} as Record<string,string>)[selection]??selection}

export function PredictionBoard(){
  const [matches,setMatches]=useState<any[]>([]);const [stake,setStake]=useState(100);const [selection,setSelection]=useState<any>(null);const [message,setMessage]=useState('');
  useEffect(()=>{fetch('/api/matches').then(r=>r.json()).then(d=>setMatches(d.matches??[]));},[]);
  const potential=selection?Math.floor(stake*selection.odds):0;
  async function place(){if(!selection)return;const r=await fetch('/api/predictions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...selection,stake})});const d=await r.json();setMessage(r.ok?`Pronóstico creado: ${d.prediction.code}`:(d.error??'No se pudo crear'));if(r.ok)setSelection(null);}
  return <div className="grid gap-5 lg:grid-cols-[1fr_340px]"><div className="space-y-4">{matches.slice(0,10).map(match=><Card key={match.id}><CardHeader><div className="flex items-center justify-between"><CardTitle className="text-base">{match.homeTeam.name} vs {match.awayTeam.name}</CardTitle><span className="text-xs text-white/40">{match.group.name}</span></div></CardHeader><CardContent><div className="grid gap-2 sm:grid-cols-3">{(match.markets??[]).map((m:any)=><button key={m.id} onClick={()=>setSelection({matchId:match.id,market:m.market,selection:m.selection,odds:m.odds})} className={`rounded-xl border px-3 py-3 text-left ${selection?.matchId===match.id&&selection?.selection===m.selection&&selection?.market===m.market?'border-green-500/50 bg-green-500/10':'border-white/8 bg-white/[.03] hover:bg-white/[.06]'}`}><div className="text-[11px] uppercase tracking-[.08em] text-white/35">{marketLabel(m.market)}</div><div className="mt-1 font-semibold">{selectionLabel(m.selection,match)}</div><div className="mt-1 text-lg font-black">{m.odds.toFixed(2)}</div></button>)}</div></CardContent></Card>)}</div><Card className="h-fit lg:sticky lg:top-24"><CardHeader><CardTitle>Bet Slip</CardTitle></CardHeader><CardContent><div className="rounded-xl bg-white/[.03] p-3 text-sm">{selection?<><div className="font-semibold">{selectionLabel(selection.selection,matches.find(m=>m.id===selection.matchId)??{homeTeam:{shortName:''},awayTeam:{shortName:''}})}</div><div className="mt-1 text-xs text-white/40">Cuota {selection.odds.toFixed(2)}</div></>:<div className="text-white/45">Selecciona un mercado.</div>}</div><label className="mt-4 block text-xs text-white/45">Apuesta</label><Input className="mt-2" type="number" min={10} value={stake} onChange={e=>setStake(Number(e.target.value))}/><div className="mt-4 flex justify-between text-sm"><span className="text-white/45">Premio potencial</span><b>{potential.toLocaleString('es-MX')} TDP</b></div><Button className="mt-4 w-full" disabled={!selection} onClick={place}>Confirmar pronóstico</Button>{message&&<div className="mt-3 rounded-xl bg-white/[.04] p-3 text-xs text-white/65">{message}</div>}</CardContent></Card></div>;
}
