'use client';
import { FormEvent, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';

export default function RegisterPage(){const router=useRouter();const [form,setForm]=useState({name:'',username:'',email:'',password:''});const [error,setError]=useState('');const [loading,setLoading]=useState(false);async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError('');const r=await fetch('/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();setLoading(false);if(!r.ok)return setError(d.error??'No se pudo registrar');router.push('/dashboard');router.refresh();}return <div className="grid min-h-screen place-items-center bg-[radial-gradient(circle_at_top,rgba(34,197,94,.14),transparent_30%),#050b08] p-4"><Card className="w-full max-w-md"><CardHeader><CardTitle className="text-2xl">Crear cuenta</CardTitle><p className="text-sm text-white/50">Recibe 10,000 TDP Coins virtuales de inicio.</p></CardHeader><CardContent><form onSubmit={submit} className="grid gap-3"><Input placeholder="Nombre" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Input placeholder="Username" value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/><Input type="email" placeholder="Correo" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><Input type="password" placeholder="Contraseña (8+ caracteres)" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/>{error&&<div className="rounded-xl bg-red-500/10 p-3 text-sm text-red-300">{error}</div>}<Button type="submit" disabled={loading}>{loading?'Creando...':'Crear cuenta'}</Button><Link href="/login" className="text-center text-xs text-white/45 hover:text-white">Ya tengo cuenta</Link></form></CardContent></Card></div>}
