'use client';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { RED_NUMBERS } from '@/lib/casino/roulette';

export function RouletteWheel({ initialBalance }: { initialBalance: number }) {
  const [bet, setBet] = useState(100); const [type, setType] = useState('red'); const [value, setValue] = useState('red'); const [result, setResult] = useState<number | null>(null); const [loading, setLoading] = useState(false); const [message, setMessage] = useState('Selecciona una apuesta.');
  async function spin() {
    setLoading(true); const res = await fetch('/api/casino/roulette/play', { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ bet, selectionType:type, selectionValue:value }) }); const data=await res.json(); setLoading(false); if(!res.ok) return setMessage(data.error ?? 'No se pudo jugar.'); setResult(data.game.winningNumber); setMessage(data.game.won ? `¡Ganaste! Premio: ${data.game.payout.toLocaleString('es-MX')} TDP Coins` : 'No salió esta vez.'); }
  const red = result !== null && RED_NUMBERS.has(result);
  return <div className="grid gap-5 lg:grid-cols-[1fr_320px]">
    <Card className="overflow-hidden"><div className="min-h-[500px] bg-[radial-gradient(circle_at_center,rgba(239,68,68,.1),transparent_46%),#10100f] p-6"><div className="text-xs uppercase tracking-[0.2em] text-red-300">Casino virtual</div><h2 className="mt-1 text-2xl font-black">Ruleta europea</h2><div className="mt-10 grid place-items-center"><div className={`grid size-48 place-items-center rounded-full border-[12px] border-white/20 bg-gradient-to-br from-red-500/80 via-black to-green-600/70 shadow-2xl ${loading ? 'animate-spin' : ''}`}><div className="grid size-28 place-items-center rounded-full border border-white/20 bg-black/50"><div className="text-center"><div className="text-[11px] uppercase tracking-[0.2em] text-white/50">Resultado</div><div className={`text-5xl font-black ${result === 0 ? 'text-green-400' : red ? 'text-red-400' : 'text-white'}`}>{result ?? '—'}</div></div></div></div></div><div className="mt-10 text-center text-sm text-white/65">{message}</div><div className="mt-8 flex justify-center"><Button size="lg" onClick={spin} disabled={loading}>{loading ? 'Girando...' : 'Girar ruleta'}</Button></div></div></Card>
    <Card><div className="p-5"><div className="grid gap-3"><label className="text-xs text-white/50">Apuesta</label><Input type="number" min={10} value={bet} onChange={(e)=>setBet(Number(e.target.value))}/><label className="mt-2 text-xs text-white/50">Tipo</label><select value={type} onChange={(e)=>{setType(e.target.value); setValue(e.target.value)}} className="h-11 rounded-xl border border-white/10 bg-black/20 px-3 text-sm text-white"><option value="red">Rojo</option><option value="black">Negro</option><option value="even">Par</option><option value="odd">Impar</option><option value="low">1–18</option><option value="high">19–36</option><option value="dozen">Docena</option><option value="column">Columna</option><option value="number">Número</option></select>{['number','dozen','column'].includes(type) && <Input value={value} onChange={(e)=>setValue(e.target.value)} placeholder={type === 'number' ? '0–36' : '1–3'} />}<div className="mt-4 rounded-xl bg-white/5 p-3 text-xs leading-5 text-white/50">Ruleta europea 0–36. Resultado generado en servidor. Saldo inicial mostrado: {initialBalance.toLocaleString('es-MX')} TDP Coins.</div></div></div></Card>
  </div>;
}
