import Link from 'next/link';
import { ArrowUpRight, CheckCircle2, Gamepad2, WalletCards } from 'lucide-react';
import { AppShell } from '@/components/layout/AppShell';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { requireUser } from '@/lib/auth/session';
import { prisma } from '@/lib/db/prisma';
import { formatCoins } from '@/lib/utils';

export default async function DashboardPage(){const user=await requireUser();const [predictions,recentGames]=await Promise.all([prisma.prediction.findMany({where:{userId:user.id},orderBy:{createdAt:'desc'},take:6,include:{match:{include:{homeTeam:true,awayTeam:true}}}}),prisma.blackjackGame.findMany({where:{userId:user.id},orderBy:{createdAt:'desc'},take:3})]);const settled=await prisma.prediction.count({where:{userId:user.id,status:{in:['WON','LOST']}}});const won=await prisma.prediction.count({where:{userId:user.id,status:'WON'}});const success=settled?Math.round(won/settled*100):0;return <AppShell><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="text-sm text-green-400">Hola, {user.name}</div><h1 className="mt-1 text-3xl font-black">Tu dashboard</h1></div><Link href="/wallet" className="text-sm text-white/50 hover:text-white">Ver wallet completa</Link></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Stat label="TDP Coins" value={formatCoins(user.wallet?.balance??0)} tone="green"/><Stat label="Pronósticos" value={String(await prisma.prediction.count({where:{userId:user.id}}))} tone="neutral"/><Stat label="Acertados" value={`${success}%`} tone="green"/><Stat label="Casino" value={String(recentGames.length)} tone="neutral"/></div><div className="mt-6 grid gap-5 lg:grid-cols-[1.3fr_.7fr]"><Card><CardHeader><CardTitle>Actividad reciente</CardTitle></CardHeader><CardContent className="space-y-3">{predictions.length===0?<p className="text-sm text-white/45">Aún no tienes actividad.</p>:predictions.map(p=><div key={p.id} className="flex items-center justify-between rounded-xl bg-white/[.03] p-3"><div><div className="font-semibold">{p.match.homeTeam.shortName} vs {p.match.awayTeam.shortName}</div><div className="text-xs text-white/40">{p.selection} · {p.stake} TDP</div></div><Badge variant={p.status==='WON'?'success':p.status==='LOST'?'danger':'muted'}>{p.status}</Badge></div>)}</CardContent></Card><div className="grid gap-4"><Quick href="/pronosticos" icon={CheckCircle2} title="Hacer pronóstico" text="Elige mercados simulados."/><Quick href="/casino/blackjack" icon={Gamepad2} title="Jugar Blackjack" text="Prueba una mesa virtual."/><Quick href="/wallet" icon={WalletCards} title="Revisar wallet" text="Consulta movimientos."/></div></div></AppShell>}
function Stat({label,value,tone}:{label:string;value:string;tone:string}){return <Card><CardContent><div className="text-xs uppercase tracking-[0.15em] text-white/35">{label}</div><div className={`mt-2 text-2xl font-black ${tone==='green'?'text-green-300':''}`}>{value}</div></CardContent></Card>}
function Quick({href,icon:Icon,title,text}:{href:string;icon:any;title:string;text:string}){return <Link href={href} className="group rounded-2xl border border-white/8 bg-white/[.03] p-4 hover:bg-white/[.05]"><div className="flex items-center justify-between"><div className="flex size-9 items-center justify-center rounded-xl bg-green-500/10 text-green-400"><Icon className="size-4"/></div><ArrowUpRight className="size-4 text-white/20 group-hover:text-white"/></div><div className="mt-3 font-semibold">{title}</div><div className="text-xs text-white/40">{text}</div></Link>}
